/**
  ******************************************************************************
  * @file    usbd_msc_data.c
  * @author  MCD Application Team
  * @brief   This file provides all the vital inquiry pages and sense data.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2015 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* BSPDependencies
- "stm32xxxxx_{eval}{discovery}{nucleo_144}.c"
- "stm32xxxxx_{eval}{discovery}_io.c"
- "stm32xxxxx_{eval}{discovery}{adafruit}_sd.c"
EndBSPDependencies */

/* Includes ------------------------------------------------------------------*/
#include "usbd_msc_data.h"


/** @addtogroup STM32_USB_DEVICE_LIBRARY
  * @{
  */


/** @defgroup MSC_DATA
  * @brief Mass storage info/data module
  * @{
  */

/** @defgroup MSC_DATA_Private_TypesDefinitions
  * @{
  */
/**
  * @}
  */


/** @defgroup MSC_DATA_Private_Defines
  * @{
  */
/**
  * @}
  */


/** @defgroup MSC_DATA_Private_Macros
  * @{
  */
/**
  * @}
  */


/** @defgroup MSC_DATA_Private_Variables
  * @{
  */

/* USB Mass storage Page 0 Inquiry Data */
uint8_t MSC_Page00_Inquiry_Data[LENGTH_INQUIRY_PAGE00] =
{
  0x00,
  0x00,
  0x00,
  (LENGTH_INQUIRY_PAGE00 - 4U),
  0x00,
  0x80,
  0xB0    /* Block Limits VPD page now supported -- see usbd_msc_data.h */
};

/* USB Mass storage VPD Page 0xB0 Inquiry Data: Block Limits (SBC-3).
 * Not generated by CubeMX -- added to advertise a modest OPTIMAL TRANSFER
 * LENGTH so host read-ahead (macOS Finder / Windows Explorer copy dialogs)
 * splits large reads into ~256KB chunks instead of a handful of multi-MB
 * SCSI commands, which is what made copy progress update in big, sparse
 * jumps. MAXIMUM TRANSFER LENGTH just caps how large a single command a
 * well-behaved host should issue; our own SCSI_ProcessRead/Write already
 * loop internally in MSC_MEDIA_PACKET-sized cycles regardless, so this is
 * a hint only, not a real firmware limit. Every field we have no
 * meaningful value for (UNMAP/WRITE SAME/ATOMIC -- all unsupported on
 * this read-only device) is left 0 ("not reported"), per SBC-3. */
uint8_t MSC_PageB0_Inquiry_Data[LENGTH_INQUIRY_PAGEB0] =
{
  0x00,                          /* Peripheral qualifier / device type */
  0xB0,                          /* Page code */
  0x00, 0x3CU,                   /* Page length (60) */
  0x00,                          /* WSNZ = 0 */
  0x00,                          /* MAXIMUM COMPARE AND WRITE LENGTH = 0 */
  0x00, 0x10U,                   /* OPTIMAL TRANSFER LENGTH GRANULARITY: 16 blocks (8KB) */
  0x00, 0x00, 0x08U, 0x00,       /* MAXIMUM TRANSFER LENGTH: 2048 blocks (1MB) */
  0x00, 0x00, 0x02U, 0x00,       /* OPTIMAL TRANSFER LENGTH: 512 blocks (256KB) */
  0x00, 0x00, 0x00, 0x00,        /* MAXIMUM PREFETCH XDREAD XDWRITE TRANSFER LENGTH = 0 */
  0x00, 0x00, 0x00, 0x00,        /* MAXIMUM UNMAP LBA COUNT = 0 */
  0x00, 0x00, 0x00, 0x00,        /* MAXIMUM UNMAP BLOCK DESCRIPTOR COUNT = 0 */
  0x00, 0x00, 0x00, 0x00,        /* OPTIMAL UNMAP GRANULARITY = 0 */
  0x00, 0x00, 0x00, 0x00,        /* UNMAP GRANULARITY ALIGNMENT (UGAVALID=0) = 0 */
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  /* MAXIMUM WRITE SAME LENGTH = 0 */
  0x00, 0x00, 0x00, 0x00,        /* MAXIMUM ATOMIC TRANSFER LENGTH = 0 */
  0x00, 0x00, 0x00, 0x00,        /* ATOMIC ALIGNMENT = 0 */
  0x00, 0x00, 0x00, 0x00,        /* ATOMIC TRANSFER LENGTH GRANULARITY = 0 */
  0x00, 0x00, 0x00, 0x00,        /* MAXIMUM ATOMIC TRANSFER LENGTH WITH ATOMIC BOUNDARY = 0 */
  0x00, 0x00, 0x00, 0x00         /* MAXIMUM ATOMIC BOUNDARY SIZE = 0 */
};

/* USB Mass storage VPD Page 0x80 Inquiry Data for Unit Serial Number */
uint8_t MSC_Page80_Inquiry_Data[LENGTH_INQUIRY_PAGE80] =
{
  0x00,
  0x80,
  0x00,
  LENGTH_INQUIRY_PAGE80,
  0x20,     /* Put Product Serial number */
  0x20,
  0x20,
  0x20
};

/* USB Mass storage sense 6 Data */
uint8_t MSC_Mode_Sense6_data[MODE_SENSE6_LEN] =
{
  0x03,     /* MODE DATA LENGTH. The number of bytes that follow. */
  0x00,     /* MEDIUM TYPE. 00h for SBC devices. */
  0x00,     /* DEVICE-SPECIFIC PARAMETER. For SBC devices:
             *   bit 7: WP. Set to 1 if the media is write-protected.
             *   bits 6..5: reserved
             *   bit 4: DPOFUA. Set to 1 if the device supports the DPO and FUA bits
             *   bits 3..0: reserved */
  0x00      /* BLOCK DESCRIPTOR LENGTH */
};


/* USB Mass storage sense 10 Data */
uint8_t MSC_Mode_Sense10_data[MODE_SENSE10_LEN] =
{
  0x00,     /* MODE DATA LENGTH MSB. */
  0x06,     /* MODE DATA LENGTH LSB. The number of bytes that follow. */
  0x00,     /* MEDIUM TYPE. 00h for SBC devices. */
  0x00,     /* DEVICE-SPECIFIC PARAMETER. For SBC devices:
             *   bit 7: WP. Set to 1 if the media is write-protected.
             *   bits 6..5: reserved
             *   bit 4: DPOFUA. Set to 1 if the device supports the DPO and FUA bits
             *   bits 3..0: reserved */
  0x00,     /* LONGLBA Set to zero */
  0x00,     /* Reserved */
  0x00,     /* BLOCK DESCRIPTOR LENGTH MSB. */
  0x00      /* BLOCK DESCRIPTOR LENGTH LSB. */
};
/**
  * @}
  */


/** @defgroup MSC_DATA_Private_FunctionPrototypes
  * @{
  */
/**
  * @}
  */


/** @defgroup MSC_DATA_Private_Functions
  * @{
  */

/**
  * @}
  */


/**
  * @}
  */


/**
  * @}
  */

