/*
 * MissionControl.hpp
 *
 *  Created on: Jul 3, 2026
 *      Author: karadeli
 *
 *  Mission sequencer.
 *
 *  DO NOT EDIT THIS FILE TO ADD OR CHANGE A MISSION.
 *  Every mission lives in UserTask.cpp, in the `missionTable[]` array.
 *  This file only knows how to run whatever is in that table.
 */
#ifndef MISSIONCONTROL_MISSIONCONTROL_HPP_
#define MISSIONCONTROL_MISSIONCONTROL_HPP_

#include "stdint.h"
#include "stddef.h"
#include "currentController.h"

/* Values 0..5 are unchanged so existing logs / decoders still match. */
enum class system_modes
  : int32_T {
  IDLE = 0,                 // Default value
  TESTFIRE = 1,
  HOVER = 2,
  DROP = 3,
  SHUTDOWN = 4,
  FAULT = 5,
  ARMED = 6,                // logging, actuators cold, waiting for safety pin
  SAFE_DISCHARGE = 7        // new mission kind
};

extern controller_modes controller_mode;

using Function = void (*)(uint32_t time_ms);

/* ops_duration_ms == MISSION_NO_TIMEOUT -> mission runs until it is stopped
 * by the button / UART / RequestShutdown(). Use with care. */
static const uint32_t MISSION_NO_TIMEOUT = 0xFFFFFFFFu;

/* ------------------------------------------------------------------------
 * One row of the mission table. Field order matters (positional init).
 * ------------------------------------------------------------------------ */
struct MissionDef {
	const char      *name;                    //  1 UART name, short and unique
	system_modes     kind;                    //  2 value written to the log while firing
	controller_modes actuator_mode;           //  3 controller mode during ops
	Function         task;                    //  4 ops callback,      t = ms since fire
	Function         shutdown;                //  5 shutdown callback, t = ms since shutdown
	uint32_t         ops_duration_ms;         //  6 hard cut-off (or MISSION_NO_TIMEOUT)
	uint32_t         shutdown_duration_ms;    //  7
	uint32_t         postShutdownWait_ms;     //  8 actuators DISABLEd, log still running
	uint32_t         log_estimate_ms;         //  9 estimate, used for file pre-allocation
	bool             wait_safety_release;     // 10 true -> ARM on trigger, fire on pin release
	bool             abort_on_safety_connect; // 11 true -> pin re-inserted while firing = abort
	uint32_t         arm_timeout_ms;          // 12 0 or MISSION_NO_TIMEOUT = wait forever
	const char      *header;                  // 13 log header string
};

/* ---- provided by the user team in UserTask.cpp -------------------------- */
extern const MissionDef missionTable[];
extern const uint8_t    missionTableCount;
/* true when the safety connector is OUT (pin reads 1) */
extern bool             safetyConnectorReleased();
/* ------------------------------------------------------------------------ */

class MissionControl {
public:
	MissionControl(volatile bool *log_ready, volatile bool *log_recording);

	void Init();

	/* --- selection (UART). Only allowed while idle. --- */
	bool Select(uint8_t index);
	bool Select(const char *name);
	uint8_t           SelectedIndex() const { return selected_index; }
	const MissionDef *Selected() const;   // queued by the operator
	const char       *SelectedName() const;
	const MissionDef *Active() const { return active; }   // executing now
	const char       *ActiveName() const;
	const char       *StateName() const;

	/* --- what sd_task needs to size and label the log file --- */
	const char *SelectedHeader() const;   // never null
	uint32_t    LogPreallocMs() const;    // 0 = unknown, do not pre-allocate

	/* --- control. Start()/End() act immediately, call them from task
	 *     context. From an ISR use the Request* variants below.      --- */
	bool Start();
	void End();
	void Toggle();

	void RequestStart()    { req_start = true;    }
	void RequestStop()     { req_stop = true;     }
	void RequestToggle()   { req_toggle = true;   }
	void RequestShutdown() { req_shutdown = true; }   // graceful early stop

	/* --- safe discharge: valid from ANY state, including FAULT and
	 *     mid-flight. Prefer the Request form from an ISR.            --- */
	bool SafeDischarge();
	void RequestSafeDischarge() { req_discharge = true; }
	bool HasSafeDischarge() const { return safe_index < missionTableCount; }

	void Iter();           // call at a fixed rate (pressure loop)

	/* --- UART helpers. Call from the main loop, not from an ISR (snprintf) --- */
	int  ListMissions(char *out, size_t n) const;
	int  Report(char *out, size_t n) const;
	bool HandleCommand(const char *cmd, char *reply, size_t n);

	/* --- state --- */
	controller_modes actuator_mode;
	system_modes     system_mode;

	volatile bool *log_ready;
	volatile bool *log_recording;

	bool running = false;   // mission active (ARMED | firing | SHUTDOWN) -> log
	bool firing  = false;   // ops/shutdown callbacks live, thrusters may fire

	/* mirrors of the active mission, kept for telemetry / compatibility */
	uint32_t ops_duration_ms = 0;
	uint32_t shutdown_duration_ms = 0;
	uint32_t postShutdownWait_ms = 0;

	uint32_t ops_time_counter_ms = 0;
	uint32_t ops_start_ms = 0;
	uint32_t shutdown_start_ms = 0;
	uint32_t shutdown_time_counter_ms = 0;
	uint32_t armed_start_ms = 0;
	uint32_t armed_time_counter_ms = 0;

	uint32_t safety_debounce_ms = 20;   // pin must stay released this long
	const char *last_error = "";

private:
	void BeginOps();
	void BeginShutdown();
	void SetActuatorMode(controller_modes m);
	bool SafetyReleasedDebounced();
	void ServiceRequests();

	uint8_t           selected_index = 0;
	uint8_t           safe_index = 0xFFu;   // row whose kind is SAFE_DISCHARGE
	const MissionDef *active = nullptr;     // != Selected() during a discharge
	uint32_t    safety_release_first_ms = 0;
	bool        safety_release_pending = false;

	volatile bool req_start = false;
	volatile bool req_stop = false;
	volatile bool req_toggle = false;
	volatile bool req_shutdown = false;
	volatile bool req_discharge = false;
};

extern MissionControl missionControl;

#endif /* MISSIONCONTROL_MISSIONCONTROL_HPP_ */

